### ISSUE TITLE
Operator is not defined 

### ISSUE THREAD

**Issue by Xelbak** [OGNova/r6-discord#3]
heres the full error:

```ReferenceError: operator is not defined
    at Promise (C:\Users\blake\Desktop\Jarvis\node_modules\r6-discord\index.js:13:16)
    at new Promise (<anonymous>)
    at R6.stats (C:\Users\blake\Desktop\Jarvis\node_modules\r6-discord\index.js:7:12)
    at Object.exports.run (C:\Users\blake\Desktop\Jarvis\commands\r6stats.js:17:6)
    at Client.bot.on.message (C:\Users\blake\Desktop\Jarvis\index.js:68:19)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (C:\Users\blake\Desktop\Jarvis\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\blake\Desktop\Jarvis\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\blake\Desktop\Jarvis\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
```

**Comment by Xelbak** [comment]
heres my code for reference since you haven't responded yet 

```const Discord = require("discord.js");
const R6Api = require('r6-discord');
const R6 = new R6Api();

exports.run = async (bot, message, args) => {

  message.delete();
  let username;
  let platform;

  if (!['uplay','xone','ps4'].includes(args[0])) return message.channel.send('**Please include the platform! example: `>r6stats [uplay | xone | ps4] <username>`**');
  if (!args[1]) return message.channel.send('**Please include the username! example: `>r6stats [uplay | xone | ps4] <username>`**');

  platform = args.shift();
  username = args.join(' ');

  R6.stats(username, platform).then(stats => {
    console.log(stats);
  }).catch(error => {
    console.log(error);
  });

}

exports.help = {
  name: "r6stats"
}```

as you can see I haven't put operator anywhere in my command so I would really like an update to fix this as I am still experiencing this issue and cannot develop my command atm

**Comment by OGNova** [comment]
Fixed in the latest commit!
